# Generated by Django 3.2.5 on 2021-07-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('ratin', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('site', models.CharField(max_length=29)),
                ('email', models.CharField(max_length=38, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('street', models.CharField(max_length=27)),
                ('city', models.CharField(max_length=36)),
                ('state', models.CharField(max_length=21)),
                ('lat', models.FloatField(max_length=8)),
                ('lng', models.FloatField(max_length=8)),
            ],
        ),
    ]
